updated docs

diff --git a/ocb/8.0-dev/Dockerfile b/ocb/8.0-dev/Dockerfile
--- a/ocb/8.0-dev/Dockerfile
+++ b/ocb/8.0-dev/Dockerfile
@@ -3,12 +3,11 @@ FROM oondeo/odoo-deps
 MAINTAINER Juan Ramon Alfaro <info@oondeo.es>
 
 ENV PHANTOMJS_VERSION=2.1.1 \
-    REMOTE_MODULE_INSTALLER_VERSION=0.1 \
     ODOO_VERSION=8.0
 
-ENV ODOO_MODULES_URLS="https://github.com/OCA/l10n-spain/archive/8.0.zip https://github.com/OCA/web/archive/8.0.zip https://github.com/OCA/e-commerce/archive/8.0.zip https://github.com/OCA/sale-workflow/archive/8.0.zip https://github.com/OCA/product-attribute/archive/8.0.zip https://github.com/OCA/bank-statement-import/archive/8.0.zip https://github.com/OCA/hr-timesheet/archive/8.0.zip https://github.com/OCA/product-variant/archive/8.0.zip https://github.com/OCA/account-payment/archive/8.0.zip https://github.com/OCA/website/archive/8.0.zip https://github.com/OCA/knowledge/archive/8.0.zip https://github.com/OCA/project/archive/8.0.zip https://github.com/OCA/report-print-send/archive/8.0.zip https://github.com/OCA/commission/archive/8.0.zip" \
+ENV ODOO_MODULES=""
 # Variables used by the WDB debugger, in case you link a WDB container
-    WDB_NO_BROWSER_AUTO_OPEN=True \
+ENV WDB_NO_BROWSER_AUTO_OPEN=True \
     WDB_SOCKET_SERVER=wdb \
     WDB_WEB_PORT=1984 \
     WDB_WEB_SERVER=localhost \
@@ -84,10 +83,7 @@ RUN apt-get update && apt-get install -y --no-install-recommends $BUILD_PACKAGES
     virtualenv --system-site-packages /opt/odoo/.env && \
     $PIP_BIN install $PYTHON_MODULES && \
 #----------Development---------------------------------------------
-    curl -SL -o oca_install.zip https://github.com/amon-ra/oca_install/archive/$REMOTE_MODULE_INSTALLER_VERSION.zip && \
-    unzip oca_install.zip && \
     mkdir -p $XDG_DATA_HOME/.local/share/Odoo/addons/$ODOO_VERSION && \
-    mv oca_install-$REMOTE_MODULE_INSTALLER_VERSION/oca_install $XDG_DATA_HOME/.local/share/Odoo/addons/$ODOO_VERSION/ && \
 #Install wdb for development
     $PIP_BIN install wdb && \
 # Add PhantomJS for headless ECMAScript tests
@@ -95,9 +91,10 @@ RUN apt-get update && apt-get install -y --no-install-recommends $BUILD_PACKAGES
     tar -jxf phantomjs.tar.bz2 && \
     cp phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin/phantomjs /usr/local/bin/ && \
     rm -rf phantomjs* && \
-    rm -rf /tmp/* /root/.cache
+#cleanup
+    rm -rf /tmp/* /root/.cache /var/lib/apt || true
 
 # Install odoo script
 RUN /usr/local/bin/odoo-install
 #fix permisions
-RUN chown -R odoo /usr/local/lib/python2.7 /mnt/extra-addons /opt/odoo /var/log/odoo /var/lib/odoo /home/odoo
+RUN chown -R odoo /usr/local/lib/python2.7 /var/log/odoo /var/lib/odoo /home/odoo
